# Registry credentials configuration
registries:
  - name: "${ORASHUB_REGISTRY}"
    username: "${ORASHUB_REGISTRY_USERNAME}"
    password: "${ORASHUB_REGISTRY_PASSWORD}"

# Repository access policy
allowed_repositories:
  - "${ORASHUB_REGISTRY}/codekaizen-github/*"
blocked_repositories: []
