# Registry credentials configuration
registries:
  - name: "${WORDPRESS_PLUGIN_REGISTRY_ORAS_REGISTRY}"
    username: "${WORDPRESS_PLUGIN_REGISTRY_ORAS_REGISTRY_USERNAME}"
    password: "${WORDPRESS_PLUGIN_REGISTRY_ORAS_REGISTRY_PASSWORD}"

# Repository access policy
allowed_repositories:
  - "${WORDPRESS_PLUGIN_REGISTRY_ORAS_REGISTRY}/codekaizen-github/*"
blocked_repositories: []

