allowed_repositories:
  - "docker.io/library/nginx"
  - "ghcr.io/myorg/myapp"
  - "gcr.io/myproject/*"
  - "myregistry.example.com/team/service"
blocked_repositories:
  - "docker.io/library/redis"
  - "gcr.io/evilcorp/*"
