name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags that start with "v"

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - server
          # - client # Uncomment if you want to build the client as well
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
        include:
          # Add binary names based on component
          - component: server
            binary_name: orashub
          # - component: client
          #   binary_name: orashubctl
          # Add suffixes for Windows
          - goos: windows
            suffix: ".exe"
          # Add empty suffix for non-Windows platforms
          - goos: linux
            suffix: ""
          - goos: darwin
            suffix: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Adjust to your Go version

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          # Extract version from tag (e.g., v1.2.3 -> 1.2.3)
          VERSION=${GITHUB_REF#refs/tags/v}
          # Get current date
          BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          # Get suffix (default to empty string if not defined)
          SUFFIX="${{ matrix.suffix || '' }}"
          # Build with version info
          go build -v \
            -ldflags "-X main.version=${VERSION} -X main.commit=${GITHUB_SHA} -X main.date=${BUILD_DATE}" \
            -o "${{ matrix.binary_name || 'orashub' }}-${{ matrix.goos }}-${{ matrix.goarch }}${SUFFIX}" \
            ./${{ matrix.component }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary_name || 'orashub' }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ${{ matrix.binary_name || 'orashub' }}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.suffix || '' }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            orashub-*/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
